### ISSUE TITLE
Doesn't track anything except exp

### ISSUE THREAD

**Issue by Prongles4** [RaraProjects/metrics#11]
Doesn't track anything except exp and I have to unload and load to get it to work. I have the July 29th 2024 version.

**Comment by Prongles4** [comment]
![Screenshot (407)](https://github.com/user-attachments/assets/27abf6f2-2588-461d-b275-4a804456c1ab)

Now it's only showing wyvern damage

**Comment by RaraProjects** [comment]
This happens to me when I first log in sometimes. Is that when you're seeing the issue too or does it work and then not work suddenly?

**Comment by Prongles4** [comment]
Yeah, I think it is when I first login sometimes. Not always. After I unload and load it doesn't happen again.

**Comment by RaraProjects** [comment]
I found the issue. It's a pretty simple fix. I'm planning the release strategy. Thanks for bringing this up.

The issue was with a party refresh flag that I didn't set upon initial load. If you were to join a party then that flag would be set and it should work okay. In short, the issue primarily affects players that go out and immediately do something solo which is probably why I haven't heard more about it.

**Comment by RaraProjects** [comment]
The fix is released! Sorry it took so long to get out to the main branch.
